version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8066:80"
    volumes:
      - .:/var/www/html/
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data/:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend:
